version: "3.4"
services:
  postgres:
    hostname: postgres
    image: postgres:14
    restart: always
    volumes:
      - ./postgres/create_db.sh:/docker-entrypoint-initdb.d/20-create_db.sh
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: itsasecret
      POSTGRES_USER: dendrite
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dendrite"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

  monolith:
    hostname: monolith
    image: matrixdotorg/dendrite-monolith:latest
    command: [
      "--tls-cert=server.crt",
      "--tls-key=server.key"
    ]
    volumes:
      - ./config:/etc/dendrite
      - ./media:/var/dendrite/media
    depends_on:
      - postgres
    networks:
      - internal
      - traefik
    restart: unless-stopped
    labels:
        - "traefik.http.routers.monolith.rule=Host(`matrix.shorty.systems`)"
        - "traefik.http.routers.monolith.tls=true"
        - "traefik.http.routers.monolith.tls.certresolver=default"
        - "traefik.http.services.monolith.loadbalancer.server.port=8008"
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"

networks:
  internal:
    attachable: true
  traefik:
    external: true
