version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "./data:/data"
      - "/home/dietpi/test:/music:ro"
    networks:
      - traefik
    labels:
        - "traefik.http.routers.navidrome.rule=Host(`navidrome.shorty.systems`)"
        - "traefik.http.routers.navidrome.tls=true"
        - "traefik.http.routers.navidrome.tls.certresolver=default"
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"

networks:
    traefik:
       external: true
