global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

log:
  level: ERROR

accessLog:
  filePath: "/config/access.log"
  format: json

api:
  dashboard: true

providers:
  docker:
    endpoint: tcp://traefik-proxy:2375
    exposedByDefault: false

  file:
    directory: /config/file-providers

certificatesResolvers:
  default:
    acme:
      email: REPLACE_ME
      storage: /config/acme.json
      httpChallenge:
        entryPoint: web 
  dns:
    acme:
      email: REPLACE_ME
      storage: /config/acme.json
      dnsChallenge:
        provider: cloudflare
