version: '3.5'

services:
  bot:
    image: wilsonthewolf/isfb
    container_name: isfb
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
    restart: on-failure:5
    stop_grace_period: 10s
    networks:
      - traefik
    labels:
        - "traefik.http.routers.isfb.rule=Host(`isfb.shorty.systems`)"
        - "traefik.http.routers.isfb.tls=true"
        - "traefik.http.routers.isfb.tls.certresolver=default"
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"

networks:
    traefik:
       external: true

