version: "3"

services:
  webserver:
    image: nginx
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./www:/www
    environment:
      - NGINX_PORT=80
    networks:
      - traefik
    labels:
      - "traefik.http.routers.webserver.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.webserver.tls=true"
      - "traefik.http.routers.webserver.tls.certresolver=default"
      - "traefik.http.routers.webserver.priority=1"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
