version: '3.5'

services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    volumes:
      - ./grafana_data:/var/lib/grafana
    restart: on-failure:5
    stop_grace_period: 10s
    environment:
    - GF_AUTH_ANONYMOUS_ENABLED=true
    networks:
      - traefik
    labels:
        - "traefik.http.routers.grafana.rule=Host(`grafana.shorty.systems`)"
        - "traefik.http.routers.grafana.tls=true"
        - "traefik.http.routers.grafana.tls.certresolver=default"
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    # command:
      # - '--config.file=/etc/prometheus/prometheus.yml'
      # - '--storage.tsdb.path=/prometheus'
      # - '--web.console.libraries=/etc/prometheus/console_libraries'
      # - '--web.console.templates=/etc/prometheus/consoles'
      # - '--web.enable-lifecycle'
    networks:
      - prometheus

networks:
    traefik:
       external: true

    prometheus:
